version: '3.8'

services:
  server:
    container_name: nest_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
  db:
    container_name: nest_db
    image: mongo:7.0.0-rc4
    restart: always
    ports:
      - '27018:27017'
    volumes: 
      - ./.docker/db:/data/configdb
  redis:
    container_name: nest_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "6377:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - './.docker/redis:/data'
